###
POST http://localhost:8080/api/v1/users/signUp
Content-Type: application/json

{
  "fullName": "Ebuka Ibeh",
  "email": "ebuks@gmail.com",
  "age": 43,
  "address": "55 Rave road"
}

###
GET http://localhost:8080/api/v1/users/allUser

###
GET http://localhost:8080/api/v1/users/id/1

###
GET http://localhost:8080/api/v1/users/email/marry@gmail.com

###
GET http://localhost:8080/api/v1/users/name/Marry Jane

###
PUT http://localhost:8080/api/v1/users/update/2
Content-Type: application/json

{
  "fullName": "Marry James",
  "email": "marry@gmail.com",
  "age": 22,
  "address": "44, Ruxton road"
}

###
DELETE http://localhost:8080/api/v1/users/delete/2

###
GET http://localhost:8080/api/v1/users/id/4
